version: 2.1
description: Use SOOS to find, fix and monitor known vulnerabilities in your app dependencies. To use this orb you need to have a registered account with SOOS and an API token.
display:
  source_url: https://github.com/soos-io/soos-ci-analysis-circleci-orb
  home_url: https://soos.io/

# ***************************
commands:
# ***************************
  run-analysis:
    description: >
      This command executes the SOOS analysis.
    # What will this command do?
    # Descriptions should be short, simple, and clear.
    parameters:
      project_name:
        default: "SOOS CircleCI Template"
        description: >
          The project name that will be displayed on the dashboard
        type: string
      integration_name:
        description: >
          Integration name to bind this analysis to, internal use only.
        default: "CircleCI"
        type: string
      client_id:
        description: >
          SOOS Client Id. Get it from SOOS Application.
        type: string
      api_key:
        description: >
          SOOS API Key. Get it from SOOS Application
        type: string
      mode:
        description: >
          This parameter dictates type of analysis:
           - run_and_wait: The process will submit manifest files and wait for analysis result before exiting. (Default)
           - async_init: The process will submit manifest files and exit. Requires a subsequent call with mode "async_result" to get analysis result.
           - async_result: The process will search for analysis URL file written in async_init process and execute call to URL until analysis results are available.
        type: enum 
        enum: ["run_and_wait", "async_init", "async_result"]
        default: "run_and_wait"
      on_failure:
        type: enum
        enum: ["fail_the_build", "continue_on_failure"]
        default: "fail_the_build"
      directories_to_exclude:
        description: >
          List of directories (comma separated) that you want to exclude from the scan, eg: node_modules.
        type: string
        default: "soos"
      files_to_exclude:
        description: >
          List of files (comma separated) that you want to exclude from the scan, eg: package.json.
        type: string
        default: ""
      working_directory:
        type: string
        default: "/home/circleci/integration-test-circleci"
      analysis_result_max_wait:
        description: >
          Maximum seconds to wait for Analysis Result before exiting with error.
        type: integer
        default: 300
      analysis_result_polling_interval:
        description: >
          Polling interval (in seconds) for analysis result completion (success/failure.). Min 10.
        type: integer
        default: 10
      fs_debug:
        description: >
          Enables printing of debug statements from the Orb
        type: boolean
        default: false
      api_base_url:
        description: >
          URL of the api to be used, internal use only.
        type: string
        default: "https://api.soos.io/api/"
    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      - run:
          name: Create the soos dir
          command: mkdir -p soos/workspace
      - run: |
          cd soos/workspace
          curl -s https://api.github.com/repos/soos-io/soos-ci-analysis-python/releases/latest | grep "browser_download_url" | cut -d '"' -f 4 | xargs -n 1 curl -LO
      - run:
          command: |
            pipenv install -r soos/workspace/requirements.txt
            pip install requests
          name: Install Python deps in a venv
      - run:
          name: 'Run Analysis'
          command: |
            python soos/workspace/soos.py -cid="<<parameters.client_id>>" \ 
              -akey="<<parameters.api_key>>" \
              -m="<<parameters.mode>>" \
              -of="<<parameters.on_failure>>" \
              -dte="<<parameters.directories_to_exclude>>" \
              -fte="<<parameters.files_to_exclude>>" \
              -wd="<<parameters.working_directory>>" \
              -armw="<<parameters.analysis_result_max_wait>>" \
              -arpi="<<parameters.analysis_result_polling_interval>>" \
              -blduri=$CIRCLE_BUILD_URL -ch=$CIRCLE_SHA1 -bn=$CIRCLE_BRANCH \
              -intn="<<parameters.integration_name>>" \
              -buri="<<parameters.api_base_url>>" \
              -scp="<<parameters.working_directory>>" \
              -pn="<<parameters.project_name>>"
# ***************************
# ***************************
executors:
  python:
    description: >
      This is the Python executor used to run the script.
    docker:
      - image: 'cimg/python:<<parameters.tag>>'
    parameters:
      tag:
        default: 3.9.7
        description: >
          Pick a specific circleci/python image variant:
          https://hub.docker.com/r/cimg/python/tags
        type: string
# ***************************
# ***************************
examples:
  async-analysis-with-blocking-result:
    description: |
      Run the SOOS security analysis in async_init mode.
      The process will first execute the async_init job.
      After async_init, the process will execute the async_result job to get results.
      Functionally equivalent to the synchronous-analysis-with-blocking-result example
      and is for illustrative purposes only.
    usage:
      version: "2.1"
      orbs:
        soos: soos-io/sca@X.Y.Z
      workflows:
        main:
          jobs:
            # POSSIBLE STEPS FOR YOUR ORGANIZATION'S CI WORKFLOW GO HERE
            - soos/analysis_async_init:
                client_id: "<<SOOS Client Id>>"
                api_key: "<<SOOS API Key>>"
            # POSSIBLE STEPS FOR YOUR ORGANIZATION'S CI WORKFLOW GO HERE

            - soos/analysis_async_result:
                client_id: "<<SOOS Client Id>>"
                api_key: "<<SOOS API Key>>"
                requires:
                  - soos/analysis_async_init

            # POSSIBLE STEPS FOR YOUR ORGANIZATION'S CI WORKFLOW GO HERE

  synchronous-analysis-with-blocking-result:
    description: >
      Run the SOOS security analysis in run_and_wait mode.
      The process will start and completely end within one job.
    usage:
      version: "2.1"
      orbs:
        soos: soos-io/sca@X.Y.Z
      workflows:
        main:
          jobs:
            # POSSIBLE STEPS FOR YOUR ORGANIZATION'S CI WORKFLOW GO HERE
            - soos/analysis_run_and_wait:
                client_id: "<<SOOS Client Id>>"
                api_key: "<<SOOS API Key>>"
            # POSSIBLE STEPS FOR YOUR ORGANIZATION'S CI WORKFLOW GO HERE

  async-analysis-init:
    description: >
      Run the SOOS security analysis in async_init mode.
      The process will issue a request to Package Aware to begin analysis.
      The process will not wait for the results of the analysis.
      May be run as a standalone process inside of a CI workflow or paired
      with the async-analysis-result example (with dependency set on
      the async-analysis-init job as shown in the async-analysis-with-blocking-result
      example)
    usage:
      version: "2.1"
      orbs:
        soos: soos-io/sca@X.Y.Z
      workflows:
        main:
          jobs:

            # POSSIBLE STEPS FOR YOUR ORGANIZATION'S CI WORKFLOW GO HERE
            - soos/analysis_async_init:
                client_id: "<<SOOS Client Id>>"
                api_key: "<<SOOS API Key>>"

            # POSSIBLE STEPS FOR YOUR ORGANIZATION'S CI WORKFLOW GO HERE

  async-analysis-result:
    description: >
      Run the SOOS security analysis in async_result mode.
      The process will sit and wait until the results of the analysis
      performed in the async-analysis-init example are complete (or time-out occurs.)

    usage:
      version: "2.1"
      orbs:
        soos: soos-io/sca@X.Y.Z
      workflows:
        main:
          jobs:
            # POSSIBLE STEPS FOR YOUR ORGANIZATION'S CI WORKFLOW GO HERE
            - packageaware/analysis_async_result:
                client_id: "<<SOOS Client Id>>"
                api_key: "<<SOOS API Key>>"
                requires:
                  - soos/analysis_async_init

            # POSSIBLE STEPS FOR YOUR ORGANIZATION'S CI WORKFLOW GO HERE
# ***************************
# ***************************
jobs:
  # ***************************
  soos-analysis:
  # ***************************
    description: >
      Run the SOOS security analysis in custom mode with full control.
      Mode parameter will dictate type of analysis
    # What will this job do?
    # Descriptions should be short, simple, and clear.
    parameters:
      project_name:
        default: "SOOS CircleCI Template"
        description: >
          The project name that will be displayed on the dashboard
        type: string
      integration_name:
        description: >
          Integration name to bind this analysis to, internal use only.
        default: "CircleCI"
        type: string
      client_id:
        description: >
          SOOS Client Id. Get it from SOOS Application.
        type: string
      api_key:
        description: >
          SOOS API Key. Get it from SOOS Application
        type: string
      mode:
        default: "run_and_wait"
        description: >
          This parameter dictates type of analysis:
           - run_and_wait: The process will submit manifest files and wait for analysis result before exiting. (Default)
           - async_init: The process will submit manifest files and exit. Requires a subsequent call with mode "async_result" to get analysis result.
           - async_result: The process will search for analysis URL file written in async_init process and execute call to URL until analysis results are available.
        type: enum
        enum: ["run_and_wait", "async_init", "async_result"]
      on_failure:
        type: enum
        enum: ["fail_the_build", "continue_on_failure"]
        default: "fail_the_build"
      directories_to_exclude:
        description: >
          List of directories (comma separated) that you want to exclude from the scan, eg: node_modules.
        type: string
        default: "soos"
      files_to_exclude:
        description: >
          List of files (comma separated) that you want to exclude from the scan, eg: package.json.
        type: string
        default: ""
      working_directory:
        type: string
        default: "/home/circleci/integration-test-circleci"
      analysis_result_max_wait:
        description: >
          Maximum seconds to wait for Analysis Result before exiting with error.
        type: integer
        default: 300
      analysis_result_polling_interval:
        description: >
          Polling interval (in seconds) for analysis result completion (success/failure.). Min 10.
        type: integer
        default: 10
      fs_debug:
        description: >
          Enables printing of debug statements from the Orb
        type: boolean
        default: false
      api_base_url:
        description: >
          URL of the api to be used, internal use only.
        type: string
        default: "https://api.soos.io/api/"
    working_directory: ~/integration-test-circleci
    executor:
      name: python
    steps:
      - run-analysis:
          project_name: '<<parameters.project_name>>'
          integration_name: '<<parameters.integration_name>>'
          client_id: '<<parameters.client_id>>'
          api_key: '<<parameters.api_key>>'
          mode: '<<parameters.mode>>'
          on_failure: '<<parameters.on_failure>>'
          directories_to_exclude: '<<parameters.directories_to_exclude>>'
          files_to_exclude: '<<parameters.files_to_exclude>>'
          working_directory: '<<parameters.working_directory>>'
          analysis_result_max_wait: '<<parameters.analysis_result_max_wait>>'
          analysis_result_polling_interval: '<<parameters.analysis_result_polling_interval>>'
          fs_debug: '<<parameters.fs_debug>>'
          api_base_url: '<<parameters.api_base_url>>'
# ***************************

# ***************************
  analysis_run_and_wait:
# ***************************
    description: >
      Run the SOOS security analysis in run_and_wait mode with full control.
    parameters:
      project_name:
        default: "SOOS CircleCI Template"
        description: >
          The project name that will be displayed on the dashboard
        type: string
      integration_name:
        default: "CircleCI"
        type: string
      client_id:
        type: string
      api_key:
        type: string
      on_failure:
        type: enum
        enum: ["fail_the_build", "continue_on_failure"]
        default: "fail_the_build"
      directories_to_exclude:
        type: string
        default: "soos"
      files_to_exclude:
        type: string
        default: ""
      working_directory:
        type: string
        default: "/home/circleci/integration-test-circleci"
      analysis_result_max_wait:
        type: integer
        default: 300
      analysis_result_polling_interval:
        type: integer
        default: 10
      fs_debug:
        type: boolean
        default: false
      api_base_url:
        type: string
        default: "https://api.soos.io/api/"
    working_directory: ~/integration-test-circleci
    executor:
      name: python
    steps:
      - run-analysis:
          project_name: '<<parameters.project_name>>'
          integration_name: '<<parameters.integration_name>>'
          client_id: '<<parameters.client_id>>'
          api_key: '<<parameters.api_key>>'
          mode: 'run_and_wait'
          on_failure: '<<parameters.on_failure>>'
          directories_to_exclude: '<<parameters.directories_to_exclude>>'
          files_to_exclude: '<<parameters.files_to_exclude>>'
          working_directory: '<<parameters.working_directory>>'
          analysis_result_max_wait: '<<parameters.analysis_result_max_wait>>'
          analysis_result_polling_interval: '<<parameters.analysis_result_polling_interval>>'
          fs_debug: '<<parameters.fs_debug>>'
          api_base_url: '<<parameters.api_base_url>>'
# ***************************
# ***************************
  analysis_async_init:
# ***************************
    description: >
      Run the SOOS security analysis in async_init mode with full control.
    parameters:
      project_name:
        default: "SOOS CircleCI Template"
        description: >
          The project name that will be displayed on the dashboard
        type: string
      integration_name:
        default: "CircleCI"
        type: string
      client_id:
        type: string
      api_key:
        type: string
      on_failure:
        type: enum
        enum: ["fail_the_build", "continue_on_failure"]
        default: "fail_the_build"
      directories_to_exclude:
        type: string
        default: "soos"
      files_to_exclude:
        type: string
        default: ""
      working_directory:
        type: string
        default: "/home/circleci/integration-test-circleci"
      analysis_result_max_wait:
        type: integer
        default: 300
      analysis_result_polling_interval:
        type: integer
        default: 10
      fs_debug:
        type: boolean
        default: false
      api_base_url:
        type: string
        default: "https://api.soos.io/api/"
    working_directory: ~/integration-test-circleci
    executor:
      name: python
    steps:
      - run-analysis:
          project_name: '<<parameters.project_name>>'
          integration_name: '<<parameters.integration_name>>'
          client_id: '<<parameters.client_id>>'
          api_key: '<<parameters.api_key>>'
          mode: 'async_init'
          on_failure: '<<parameters.on_failure>>'
          directories_to_exclude: '<<parameters.directories_to_exclude>>'
          files_to_exclude: '<<parameters.files_to_exclude>>'
          working_directory: '<<parameters.working_directory>>'
          analysis_result_max_wait: '<<parameters.analysis_result_max_wait>>'
          analysis_result_polling_interval: '<<parameters.analysis_result_polling_interval>>'
          fs_debug: '<<parameters.fs_debug>>'
          api_base_url: '<<parameters.api_base_url>>'
# ***************************
# ***************************
  analysis_async_result:
# ***************************
    description: >
      Run the SOOS security analysis in async_result mode with full control.
    parameters:
      project_name:
        default: "SOOS CircleCI Template"
        description: >
          The project name that will be displayed on the dashboard
        type: string
      integration_name:
        default: "CircleCI"
        type: string
      client_id:
        type: string
      api_key:
        type: string
      on_failure:
        type: enum
        enum: ["fail_the_build", "continue_on_failure"]
        default: "fail_the_build"
      directories_to_exclude:
        type: string
        default: "soos"
      files_to_exclude:
        type: string
        default: ""
      working_directory:
        type: string
        default: "/home/circleci/integration-test-circleci"
      analysis_result_max_wait:
        type: integer
        default: 300
      analysis_result_polling_interval:
        type: integer
        default: 10
      fs_debug:
        type: boolean
        default: false
      api_base_url:
        type: string
        default: "https://api.soos.io/api/"
    working_directory: ~/integration-test-circleci
    executor:
      name: python
    steps:
      - run-analysis:
          project_name: '<<parameters.project_name>>'
          integration_name: '<<parameters.integration_name>>'
          client_id: '<<parameters.client_id>>'
          api_key: '<<parameters.api_key>>'
          mode: 'async_result'
          on_failure: '<<parameters.on_failure>>'
          directories_to_exclude: '<<parameters.directories_to_exclude>>'
          files_to_exclude: '<<parameters.files_to_exclude>>'
          working_directory: '<<parameters.working_directory>>'
          analysis_result_max_wait: '<<parameters.analysis_result_max_wait>>'
          analysis_result_polling_interval: '<<parameters.analysis_result_polling_interval>>'
          fs_debug: '<<parameters.fs_debug>>'
          api_base_url: '<<parameters.api_base_url>>'
# ***************************
