description: >
  This is the Node executor used to run the script.
docker:
  - image: 'cimg/node:<<parameters.tag>>'
parameters:
  tag:
    default: 20.16.0
    description: >
      Pick a specific circleci/node image variant:
      https://hub.docker.com/r/cimg/node/tags
    type: string
