description: >
  This is the Python executor used to run the script.
docker:
  - image: 'cimg/python:<<parameters.tag>>'
parameters:
  tag:
    default: 3.10.5
    description: >
      Pick a specific circleci/python image variant:
      https://hub.docker.com/r/cimg/python/tags
    type: string
